version: '3'
services:
  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile.zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    ports:
      - "9092:9092"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    depends_on:
      - zookeeper

  kafka-manager:
    build:
      context: .
      dockerfile: Dockerfile.kafka-manager
    ports:
      - "9000:9000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    depends_on:
      - kafka