# Kafka Manager Dockerfile
FROM ubuntu:22.04

ENV KAFKA_MANAGER_VERSION 3.0.0.5
ENV KAFKA_MANAGER_HOME /opt/kafka-manager

# Java 설치
RUN apt-get update && apt-get install -y openjdk-11-jdk

# unzip 설치
RUN apt-get install -y unzip

WORKDIR /tmp
COPY kafka-manager-$KAFKA_MANAGER_VERSION.zip /tmp/
RUN unzip kafka-manager-$KAFKA_MANAGER_VERSION.zip -d /opt \
    && mv /opt/kafka-manager-$KAFKA_MANAGER_VERSION $KAFKA_MANAGER_HOME \
    && rm -rf /tmp/*

EXPOSE 9000

WORKDIR $KAFKA_MANAGER_HOME